language: python
python:
  - "3.6"
sudo: required
services:
  - docker
env:
  DOCKER_COMPOSE_VERSION: 1.8.0

before_install:
  - sudo apt-get update
  - curl -L https://github.com/docker/compose/releases/download/${DOCKER_COMPOSE_VERSION}/docker-compose-`uname -s`-`uname -m` > docker-compose
  - chmod +x docker-compose
  - sudo mv docker-compose /usr/local/bin

  - docker-compose --version

  - docker-compose -f behave.yml build
  - docker-compose -f behave.yml up -d
  - docker ps -a
  - sleep 20
  - docker ps -a

  # - chmod +x ./test.sh
  # - ./test.sh

install:
  - cd behave-data
  - pip install -r requirements.txt
before_script:
  - docker ps -a
script:
  - behave

after_success:
  - aws s3 sync reports/ s3://travis-acropolis/reports-$TRAVIS_COMMIT


after_script:
  - cd ..
  - docker-compose -f behave.yml down
