language: generic
sudo: required
services:
  - docker
env:
  DOCKER_COMPOSE_VERSION: 1.8.0

before_install:
  - sudo apt-get update
  - curl -L https://github.com/docker/compose/releases/download/${DOCKER_COMPOSE_VERSION}/docker-compose-`uname -s`-`uname -m` > docker-compose
  - chmod +x docker-compose
  - sudo mv docker-compose /usr/local/bin

  - docker-compose --version

  - docker-compose -f behave.yml build
  - docker-compose -f behave.yml up -d acropolis-bdd
  - sleep 20

  # - chmod +x ./test.sh
  # - ./test.sh

before_script:
  - docker-compose -f behave.yml up -d behave
  - docker ps
script:
  - docker logs behave > bddresult.log
	- cat bddresult.log

after_script:
  - docker-compose -f behave.yml down
